// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jmifqifhumjywfsquwpt.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImptaWZxaWZodW1qeXdmc3F1d3B0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg3Njg5MDEsImV4cCI6MjA3NDM0NDkwMX0.jr3OuPOLVE-iW4EKX3dFE0iHkEPDFTOcS5ZfVMKHHD0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});